### ISSUE TITLE
node 7.5 / edge 7.10.1 - TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by smaglio81** [MattHodge/PoshHubot#6]
Hello,

Thanks for this excellent tooling.

We have a working edition of hubot installed using PoshHubot, which is running on node 5.10.1 / edge 5.0.0 / edge-ps 0.1.0-pre.

However, I tried to do a new installation and am getting errors. Upon install, chocolatey did it's job of grabbing the latest node version, 7.5. But, edge 5.0.0 isn't precompiled to work with node 7.5, so I had Install-HubotScript get the latest version, 7.10.1. Unfortunately, I get back this error:

(note: I updated node_modules/hubot/src/robot.coffee:401 to add `@logger.debug "Loading #{pkg}"`)
```
...
[Wed May 24 2017 20:02:13 GMT+0000 (Coordinated Universal Time)] DEBUG Loading hubot-shipit
[Wed May 24 2017 20:02:13 GMT+0000 (Coordinated Universal Time)] DEBUG Loading edge
[Wed May 24 2017 20:02:13 GMT+0000 (Coordinated Universal Time)]
ERROR Error loading scripts from npm package - TypeError: require(...) is not a function
  at Robot.loadExternalScripts (D:\Projects\SAIT\Hubot\node_modules\hubot\src\robot.coffee:402:11, <js>:273:39)
  at D:\Projects\SAIT\Hubot\node_modules\hubot\bin\hubot:152:11, <js>:159:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

[config.json](https://gist.github.com/smaglio81/b1ccad2d5492cd48b72490ab93f52039)
[setup script](https://gist.github.com/smaglio81/fabe302501eef2cd89b9f7280e30ae79) (I built a clean VM on Azure and ran this on it)
[sysbot.log](https://gist.github.com/smaglio81/ff07f131657c1e54024e092228607440)

I'm very new to node & edge. From the best I can tell, google results are saying that `require('edge')` should be returning a function which is invoked on `robot.coffee:401`. But, for some reason, this version of edge isn't returning a function?

Any advice would be great. Thanks!

**Comment by brucellino** [comment]
I had the same problem. https://github.com/slackapi/hubot-slack/issues/197#issuecomment-151677985 solved it for me: Remove the slack client external script.

Hope this helps :)

**Comment by smaglio81** [comment]
Thanks for advice @brucellino. Unfortunately, it didn't work for me. I didn't have `hubot-slack` defined in my `external-scripts.json`. Looks like someone else took care of that for me.

I continue to try and upgrade it, but I'm just soo unknowledgeable about nodejs that I'm not moving very fast.

The last effort was to:

* Upgrade node from 5.10.0 to 7.10.0 (results in [an error](https://gist.github.com/smaglio81/ebf8f30c9acdd95dc3b82f08f2581a83) that wants version 7.10.0 of edge)
* Upgrade edge to 5.0.0 to 7.10.0 which results in the error below.

```
PS C:\workspace\ApiGatewayHubot> npm install edge@7.10.0

> edge-cs@1.2.1 install C:\workspace\ApiGatewayHubot\node_modules\edge-cs
> node tools/install.js

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.

Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include command-line arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.

Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline
access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 11017 ms
Expanding 100% 35125 ms
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

> edge@7.10.0 install C:\workspace\ApiGatewayHubot\node_modules\edge
> node tools/install.js

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution fife.
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solutionn file.
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.                                                                         fi
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solutionn file.
Success: platform check for edge.js: node.js x64 v7.10.0
dpb@0.0.0 C:\workspace\ApiGatewayHubot
`-- edge@7.10.0  invalid
  +-- edge-cs@1.2.1
  `-- nan@2.8.0
```

I'll just keep trying.
